# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-rc-2
loader_version=0.18.4
# Mod Properties
mod_version=handled.by.jgitver
maven_group=net.openbagtwo
archives_base_name=fox-nap
# Dependencies (optional or otherwise)
fabric_version=0.144.0+26.1
modmenu_version=18.0.0-alpha.6
snakeyaml_version=2.2
