# Rebuild the mod both to catch errors and to produce
# a compiled jar for testing (or manual publishing)

name: build_mod
on: # run on any push to the supported version branches,
  # or force building by opening a PR to anywhere
  pull_request:
  push:
    branches:
      - 1.20
      - 1.19.4

jobs:
  build_mod:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]  # have yet to come across a cross-platform Java build issue
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # TODO: try removing this after the initial release
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'  # is there a reason Fabric uses Microsoft?
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/libs/
